blank_issues_enabled: false
contact_links:
  - name: Questions or Support
    url: https://github.com/eliechevalier-cloud/CZI-Central/discussions
    about: Ask questions or get help with the project
