blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussion GÃ©nÃ©rale
    url: https://github.com/eliechevalier-cloud/CZI-Central/discussions
    about: Pour des discussions gÃ©nÃ©rales ou questions sur le projet
